### ISSUE TITLE
Unable to run danger-swift on Travis CI or locally

### ISSUE THREAD

**Issue by tylermilner** [danger/swift#101]
I'm just getting started with Danger, setting it up for an open source project that I manage that uses Travis CI. I've setup my `Dangerfile.swift` and `.travis.yml` based on the [Danger in Swift guide](https://danger.systems/js/swift.html). [Here](https://github.com/BottleRocketStudios/iOS-Hyperspace/pull/74/files) is the relevant PR that introduces Danger into my project.

Unfortunately, Travis CI [fails my build](https://travis-ci.org/BottleRocketStudios/iOS-Hyperspace/jobs/454697734#L2158) due to an `Unhandled 'error' event` error that occurs in `events.js`.

I tried to run Danger locally as well, using the `danger-swift pr https://github.com/BottleRocketStudios/iOS-Hyperspace/pull/74` command, but that fails as well (with a different error). Here is my console output from running that command:
````
danger-swift pr https://github.com/BottleRocketStudios/iOS-Hyperspace/pull/74
Running: /Users/tyler.milner/.nvm/versions/node/v8.12.0/bin/danger pr --process danger-swift https://github.com/BottleRocketStudios/iOS-Hyperspace/pull/74 
Starting Danger PR on BottleRocketStudios/iOS-Hyperspace#74
You don't have a DANGER_GITHUB_API_TOKEN set up, this is optional, but TBH, you want to do this
Check out: http://danger.systems/js/guides/the_dangerfile.html#working-on-your-dangerfile
Dangerfile.swift:2:8: error: missing required module 'ShellOut'
import Danger
     
  ^

Created a temporary file for the Dangerfile DSL at: /var/folders/00/2_dwjx0x2k12p75w98nh_z5c00012l/T/danger-dsl.json
Running Dangerfile at: Dangerfile.swift
Running: /usr/bin/swiftc --driver-mode=swift -L /usr/local/lib/danger -I /usr/local/lib/danger -lDanger -L /usr/local/lib/danger -I /usr/local/lib/danger Dangerfile.swift /var/folders/00/2_dwjx0x2k12p75w98nh_z5c00012l/T/danger-dsl.json /var/folders/00/2_dwjx0x2k12p75w98nh_z5c00012l/T/danger-response.json
Completed evaluation
ERROR: Dangerfile eval failed at Dangerfile.swift
ERROR: Could not get the results JSON file at /var/folders/00/2_dwjx0x2k12p75w98nh_z5c00012l/T/danger-response.json

Danger: ⅹ Failing the build, there is 1 fail.
## Failures
danger-swift` failed.
## Markdowns
### Log


```sh
Dangerfile.swift:2:8: error: missing required module 'ShellOut'
import Danger
       ^
Created a temporary file for the Dangerfile DSL at: /var/folders/00/2_dwjx0x2k12p75w98nh_z5c00012l/T/danger-dsl.json
Running Dangerfile at: Dangerfile.swift
Running: /usr/bin/swiftc --driver-mode=swift -L /usr/local/lib/danger -I /usr/local/lib/danger -lDanger -L /usr/local/lib/danger -I /usr/local/lib/danger Dangerfile.swift /var/folders/00/2_dwjx0x2k12p75w98nh_z5c00012l/T/danger-dsl.json /var/folders/00/2_dwjx0x2k12p75w98nh_z5c00012l/T/danger-response.json
Completed evaluation
ERROR: Dangerfile eval failed at Dangerfile.swift
ERROR: Could not get the results JSON file at /var/folders/00/2_dwjx0x2k12p75w98nh_z5c00012l/T/danger-response.json

```

````

Am I doing something horribly wrong? I'm using the latest version `0.5.1` if that helps. Thanks for your support.

**Comment by orta** [comment]
Interesting, maybe we're doing dependencies wrong in danger. I might make a release of the current build and we'll see if that fixes it

**Comment by orta** [comment]
alright, released danger swift 0.6.0 - can you give that a try?

**Comment by tylermilner** [comment]
Thanks, @orta. Version `0.6.0` works locally now with the `danger-swift pr https://github.com/BottleRocketStudios/iOS-Hyperspace/pull/74` command.

However, Travis CI is still having [build issues](https://travis-ci.org/BottleRocketStudios/iOS-Hyperspace/jobs/454795434#L2171) (same `Unhandled 'error' event` error).

**Comment by f-meloni** [comment]
@orta re: Doing dependencies wrong.
We were just not shipping the ShellOut's swiftmodule and swiftdoc.
It was fixed here https://github.com/danger/swift/pull/91

**Comment by f-meloni** [comment]
Hi @tylermilner,
We just released the version `1.0.0`
Can you please try again to see if this is still an issue please?

**Comment by tylermilner** [comment]
@f-meloni this is [working](https://github.com/BottleRocketStudios/iOS-Hyperspace/pull/74#issuecomment-451527561) for me now - both locally using the `danger-swift pr https://github.com/BottleRocketStudios/iOS-Hyperspace/pull/74` command and on Travis-CI using the `danger-swift ci` command!

I was still having issues the past couple of days trying to test things out (even after switching `danger process danger-swift` to `danger-swift ci`), but I think it was mainly due to something else screwy with my `.travis.yml` configuration. Unfortunately, I made several changes at once so I'm not sure exactly what fixed it, but here's a summary of how I reworked my Travis-CI configuration:
* Removed `npm install -g danger` from the `before_install` portion of my `.travis.yml`. 
* No longer trying to install `danger-swift` in the `before_install` portion of my `.travis.yml`. Instead, I'm using the Travis-CI [homebrew addon](https://docs.travis-ci.com/user/installing-dependencies/#installing-packages-on-os-x) - [like so](https://github.com/BottleRocketStudios/iOS-Hyperspace/pull/74/files#diff-354f30a63fb0907d4ad57269548329e3R22).
* Switched `danger process danger-swift` to `danger-swift ci` as recommended.
* Updated to the latest `xcode10.1` Travis-CI `osx_image`.

The only thing that has me slightly concerned is that one of the jobs for my build seems to have [timed out](https://travis-ci.org/BottleRocketStudios/iOS-Hyperspace/jobs/475423663#L1813) on the `danger-swift ci` command. This might be due to me running `danger-swift ci` for each job, rather than just once per build like I do for my `pod lib lint` command. I'll make this change in my Travis-CI configuration and keep an eye on it, but I think we can close this issue now. Thanks for your hard work, everyone!

**Comment by f-meloni** [comment]
@tylermilner thank you for the detailed steps, that will maybe help someone else that will end up in your same situation.
Given it looks solved, I will close this for now.

**Comment by orta** [comment]
FWIW: The timed out is likely https://github.com/danger/swift/issues/97#issuecomment-447640815 - if you're using the swiftlint plugin, you can remove that as it's now shipping with Danger Swift
